pragma Singleton

// PLEASE DO NOT EDIT THIS FILE.. IT IS GOING TO BE OVERWRITTEN BY MATUGEN

import QtQuick
import Quickshell

Singleton {
  property Item get: material

  Item {
    id: material

    // Material Design 3 color palette
    property string barBgColor: "#1F1F1F"  // Surface dark
    property string buttonBorderColor: "#2D2D2D"  // Surface variant
    property string buttonBackgroundColor: "#2D2D2D"  // Surface variant
    property bool buttonBorderShadow: false
    property bool onTop: true
    property string iconColor: "#90CAF9"  // Primary light
    property string iconPressedColor: "#64B5F6"  // Primary medium
    property string active: "#cba6f7"
  }
}

